[workspace]
resolver = "2"
members = [
    "live-object-sdk",
]
exclude = ["examples/"]

[workspace.package]
authors = ["Topology Foundation <contact@topology.gg>"]
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
license = "MIT"
